version: '3.3'

services:
            
    mongodb:
        image: mongo:4.4.1
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        ports: 
            - 27017:27017
            
    redis:
        image: redis:6.0.8-alpine
        ports: 
            - 6379:6379